language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-test-dev
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - g++-5
script:
- mkdir bin && cd bin && cmake -DBUILD_TESTS=ON .. && make && cd tests && ctest -VV
before_deploy:
- ./create_archive.sh
deploy:
  provider: releases
  api_key:
    secure: gWpJphuxYScfBynC8ZWS0bdRqqDzl7yrfokLdiVlC5/ktCt6SuJmemRPeNJJQVz8eIZVMiIf9SYzud2dUQtemYxo+bAlR5HdqGYpnJFlH7OhQejZbbiTx4qWedLyzacoZE4cTm5o3zcddHixyDFFznKLBt7POhEDk3BDb2Ta8rHsjgfp09dwIKw4SBXB9+QzS69lGLIdilDHLCA8V+4wTPqAqdOEWNI4NM9b/GEsxuGI2n0ZFCJzSjrBSRV5IduJDJ3kfChVVlpOMaIATaBvFrgRBi0AUfW6Se4BNvtSvbR2hpp+91oXqt1QdveF3dmkJk1W1zCskQuf4OS8OZoVvZ3ATNclTkGpqL08OhENaTO0vnlPA21YD/D8M8k9BsHxM82YN2uXnhehJEJ5e4gVikgxuvV73mIVass/gzAkwoqBAMVd5igsZLw53albUD5G6FmcIQSgjkLvyqKP2uQWJ+ZN+HI0n1CyMnrZWbe7Y6Tv36RtBPywqsJ3jOr67xx4yMPsavq/BY+B74qffYbh+lQ2gX56QhJO4bJelbrjioZDgbd6isWdycakmdRZQKk8esxlKx+3xp42/B4t1iGuwGndOFSUdtNz8/tNWWF9y2M9xBEJjFTumth54506+Zm2Jtq5Y/KwzwqjRraubLTzHQ+mNr2naBaUEr4axaGcRo8=
  file: ./bin/gtf2tab_x86_64.tar.gz
  on:
    tags: true
