language: cpp
os:
  - linux
  - osx
osx_image: xcode9.1
before_install:
  - sh ./ci_scripts/ubuntu_prebuild.sh
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-7" CC="gcc-7"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - jonathonf/gcc-7.1
    packages:
    - g++-7
    - libboost-test-dev
script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then mkdir bin && cd bin && ~/cmake/bin/cmake -DBUILD_TESTS=ON .. && make && cd tests && ~/cmake/bin/ctest -VV; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then mkdir bin && cd bin && cmake .. && make; fi

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: gWpJphuxYScfBynC8ZWS0bdRqqDzl7yrfokLdiVlC5/ktCt6SuJmemRPeNJJQVz8eIZVMiIf9SYzud2dUQtemYxo+bAlR5HdqGYpnJFlH7OhQejZbbiTx4qWedLyzacoZE4cTm5o3zcddHixyDFFznKLBt7POhEDk3BDb2Ta8rHsjgfp09dwIKw4SBXB9+QzS69lGLIdilDHLCA8V+4wTPqAqdOEWNI4NM9b/GEsxuGI2n0ZFCJzSjrBSRV5IduJDJ3kfChVVlpOMaIATaBvFrgRBi0AUfW6Se4BNvtSvbR2hpp+91oXqt1QdveF3dmkJk1W1zCskQuf4OS8OZoVvZ3ATNclTkGpqL08OhENaTO0vnlPA21YD/D8M8k9BsHxM82YN2uXnhehJEJ5e4gVikgxuvV73mIVass/gzAkwoqBAMVd5igsZLw53albUD5G6FmcIQSgjkLvyqKP2uQWJ+ZN+HI0n1CyMnrZWbe7Y6Tv36RtBPywqsJ3jOr67xx4yMPsavq/BY+B74qffYbh+lQ2gX56QhJO4bJelbrjioZDgbd6isWdycakmdRZQKk8esxlKx+3xp42/B4t1iGuwGndOFSUdtNz8/tNWWF9y2M9xBEJjFTumth54506+Zm2Jtq5Y/KwzwqjRraubLTzHQ+mNr2naBaUEr4axaGcRo8=
    file: $TRAVIS_BUILD_DIR/bin/gtf2tab_x86_64.tar.gz
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: gWpJphuxYScfBynC8ZWS0bdRqqDzl7yrfokLdiVlC5/ktCt6SuJmemRPeNJJQVz8eIZVMiIf9SYzud2dUQtemYxo+bAlR5HdqGYpnJFlH7OhQejZbbiTx4qWedLyzacoZE4cTm5o3zcddHixyDFFznKLBt7POhEDk3BDb2Ta8rHsjgfp09dwIKw4SBXB9+QzS69lGLIdilDHLCA8V+4wTPqAqdOEWNI4NM9b/GEsxuGI2n0ZFCJzSjrBSRV5IduJDJ3kfChVVlpOMaIATaBvFrgRBi0AUfW6Se4BNvtSvbR2hpp+91oXqt1QdveF3dmkJk1W1zCskQuf4OS8OZoVvZ3ATNclTkGpqL08OhENaTO0vnlPA21YD/D8M8k9BsHxM82YN2uXnhehJEJ5e4gVikgxuvV73mIVass/gzAkwoqBAMVd5igsZLw53albUD5G6FmcIQSgjkLvyqKP2uQWJ+ZN+HI0n1CyMnrZWbe7Y6Tv36RtBPywqsJ3jOr67xx4yMPsavq/BY+B74qffYbh+lQ2gX56QhJO4bJelbrjioZDgbd6isWdycakmdRZQKk8esxlKx+3xp42/B4t1iGuwGndOFSUdtNz8/tNWWF9y2M9xBEJjFTumth54506+Zm2Jtq5Y/KwzwqjRraubLTzHQ+mNr2naBaUEr4axaGcRo8=
    file: $TRAVIS_BUILD_DIR/bin/gtf2tab_osx.zip
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx
