os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\gtf2tab

platform: x64
configuration: Release

install:

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

before_build:
  - echo Running cmake...
  - cd c:\projects\gtf2tab
  - cmake -G "Visual Studio 14 2015 Win64"

after_build:
  - cd c:\projects\gtf2tab
  - 7z a gtf2tab_win.zip C:\projects\gtf2tab\Release\gtf2tab.exe -tzip

deploy:
  provider: GitHub
  description: 'Windows release'
  auth_token:
    secure: TkgB1ClpbVUS+9ijNYIAo2UmcULYOSeEkMbu4Ydo8nrmlmkNTq9+GqcBzAQnU+nC
  artifact: c:\projects\gtf2tab\gtf2tab_win.zip
  on:
    appveyor_repo_tag: true
